/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.raven.form;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.raven.model.HoaDon;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import com.raven.service.HoaDonService;
import com.raven.service.impl.HoaDonImpl;
import com.raven.view.ViewHoaDonCT;

public class Form_HoaDon extends javax.swing.JPanel {

    HoaDonService hdSer = new HoaDonImpl();
    List<HoaDon> list = new ArrayList<>();

    public Form_HoaDon() {
        initComponents();
        list = hdSer.getAll();
        loadTable(list);
       

    }

    public void loadTable(List<HoaDon> lst) {
        DefaultTableModel dtm = (DefaultTableModel) tblHoaDon.getModel();
        dtm.setRowCount(0);
        for (HoaDon hd : lst) {
            Object rowData[] = {
                hd.getMaHD(),
                hd.getTenXe(),
                hd.getTenNV(),
                hd.getTenKH(),
                hd.getNgayTao(),
                hd.getNgayThanhToan(),
                hd.getKhachTra(),
                hd.getTongTien(),
                hd.getSoTienGiam(),
                hd.getSdtNguoiNhan(),
                hd.getBaoHiem() == 0? "Có" : "Không",
                hd.getLamBien() == 0 ? "Có" : "Không",
                hd.getTrangThai() == 1 ? "Đã Thanh Toán" : "Chưa Thanh Toán",
                hd.getNote()
            };
            dtm.addRow(rowData);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        txtTenKH = new javax.swing.JTextField();
        txtTongTien = new javax.swing.JTextField();
        txtSoTienGiam = new javax.swing.JTextField();
        txtSoDienThoai = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtMaHD = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTenXe = new javax.swing.JTextField();
        txtTenNV = new javax.swing.JTextField();
        btnLamMoi = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        rdoYesBH = new javax.swing.JRadioButton();
        rdoNoBH = new javax.swing.JRadioButton();
        rdoYesLB = new javax.swing.JRadioButton();
        rdoNoLB = new javax.swing.JRadioButton();
        txtNgayTao = new com.toedter.calendar.JDateChooser();
        txtNgayThanhToan = new com.toedter.calendar.JDateChooser();
        cboTrangThai = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtNote = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtKhachTra = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        txtTim = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblHoaDon = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 255, 255));

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel6.setText("Ngày Tạo");

        jLabel7.setText("Ngày Thanh Toán");

        jLabel9.setText("Tổng Tiền");

        jLabel10.setText("Số Tiền Giảm");

        jLabel11.setText("Số Điện Thoại");

        jLabel12.setText("Bảo Hiểm");

        jLabel13.setText("Làm Biển");

        jLabel14.setText("Trạng Thái");

        jLabel2.setText("Mã Hóa Đơn");

        jLabel3.setText("Tên Xe");

        jLabel4.setText("Tên Nhân Viên");

        jLabel5.setText("Tên Khách Hàng");

        btnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Refresh.png"))); // NOI18N
        btnLamMoi.setText("Làm Mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Delete.png"))); // NOI18N
        btnDelete.setText("Xóa");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Edit.png"))); // NOI18N
        btnUpdate.setText("Sửa");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        rdoYesBH.setBackground(new java.awt.Color(0, 255, 255));
        buttonGroup1.add(rdoYesBH);
        rdoYesBH.setText("Có");

        rdoNoBH.setBackground(new java.awt.Color(0, 255, 255));
        buttonGroup1.add(rdoNoBH);
        rdoNoBH.setText("Không");

        rdoYesLB.setBackground(new java.awt.Color(0, 255, 255));
        buttonGroup2.add(rdoYesLB);
        rdoYesLB.setText("Có");

        rdoNoLB.setBackground(new java.awt.Color(0, 255, 255));
        buttonGroup2.add(rdoNoLB);
        rdoNoLB.setText("Không");

        cboTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đã Thanh Toán", "Chưa Thanh Toán" }));

        txtNote.setColumns(20);
        txtNote.setRows(5);
        jScrollPane2.setViewportView(txtNote);

        jLabel16.setText("Ghi chú");

        jLabel17.setText("Số tiền khách trả");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3))
                                        .addGap(32, 32, 32)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtTenXe, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtNgayThanhToan, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel5)
                                                .addComponent(jLabel6)
                                                .addComponent(jLabel4))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtTenNV)
                                                .addComponent(txtTenKH)
                                                .addComponent(txtNgayTao, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)))))
                                .addGap(147, 147, 147)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtKhachTra, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(btnUpdate)
                        .addGap(52, 52, 52)
                        .addComponent(btnDelete)
                        .addGap(26, 26, 26)
                        .addComponent(btnLamMoi)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSoTienGiam, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rdoYesBH)
                                    .addComponent(rdoYesLB))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rdoNoLB)
                                    .addComponent(rdoNoBH)))
                            .addComponent(cboTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(71, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTenXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtSoTienGiam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(rdoYesBH)
                    .addComponent(rdoNoBH))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel13)
                        .addComponent(rdoYesLB)
                        .addComponent(rdoNoLB))
                    .addComponent(txtNgayTao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jLabel14)
                        .addComponent(cboTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtNgayThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(txtKhachTra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnUpdate)
                            .addComponent(btnDelete)
                            .addComponent(btnLamMoi))
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jPanel3.setBackground(new java.awt.Color(0, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "TÌM KIẾM", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 14))); // NOI18N

        jLabel18.setText("Nhập mã Hóa đơn cần tìm");

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Search.png"))); // NOI18N
        jButton7.setText("Tìm kiếm");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTim, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(jButton7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel18)
                .addComponent(txtTim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton7))
        );

        tblHoaDon.setBackground(new java.awt.Color(0, 255, 255));
        tblHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Hóa Đơn", "Tên Xe", "Tên Nhân Viên", "Tên Khách Hàng", "Ngày Tạo", "Ngày Thanh Toán", "Khách Trả", "Tổng Tiền", "Số Tiền Giảm", "SDT", "Bảo Hiểm", "Làm Biển", "Trạng Thái", "Note"
            }
        ));
        tblHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHoaDonMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblHoaDon);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setText("DANH SÁCH HÓA ĐƠN");

        jButton5.setText("EXPORT TO EXCEL");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(284, 284, 284)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(93, 93, 93))
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
        txtMaHD.setText("");
        txtTenXe.setText("");
        txtTenNV.setText("");
        txtTenKH.setText("");
        txtTongTien.setText("");
        txtSoTienGiam.setText("");
        txtSoDienThoai.setText("");
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int trangThai = 0;
        if (cboTrangThai.getSelectedItem().toString().equalsIgnoreCase("Đã Thanh Toán")) {
            trangThai = 1;
        }
        int row = tblHoaDon.getSelectedRow();
        JOptionPane.showMessageDialog(this, hdSer.delete(tblHoaDon.getValueAt(row, 0).toString()));
        list = hdSer.getAll();
        loadTable(list);
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        HoaDon hd = new HoaDon();
        String maHd = txtMaHD.getText();
        String tenXe = txtTenXe.getText();
        String tenNv =txtTenNV.getText();
        String tenKh = txtTenKH.getText();
        String tienKhachTra = txtKhachTra.getText();
        String tongTien = txtTongTien.getText();
        String tienGiam = txtSoTienGiam.getText();
        String sdt = txtSoDienThoai.getText();
        if(maHd.trim().equals("")){
            JOptionPane.showMessageDialog(this, "Mã hóa đơn không được để trống", "Invalidation", JOptionPane.ERROR_MESSAGE);
            return;
        }else if(tenXe.trim().equals("")){
            JOptionPane.showMessageDialog(this, "Tên xe không được để trống", "Invalidation", JOptionPane.ERROR_MESSAGE);
            return;
        }else if(tenNv.trim().equals("")){
            JOptionPane.showMessageDialog(this, "Tên nhân viên không được để trống", "Invalidation", JOptionPane.ERROR_MESSAGE);
            return;
        }else if(tenKh.trim().equals("")){
            JOptionPane.showMessageDialog(this, "Tên khách hàng không được để trống", "Invalidation", JOptionPane.ERROR_MESSAGE);
            return;
        }else if(tienKhachTra.trim().equals("")){
            JOptionPane.showMessageDialog(this, "Tiền khách trả không được để trống", "Invalidation", JOptionPane.ERROR_MESSAGE);
            return;
        }else if(tongTien.trim().equals("")){
            JOptionPane.showMessageDialog(this, "Tổng tiền không được để trống", "Invalidation", JOptionPane.ERROR_MESSAGE);
            return;
        }else if(tienGiam.trim().equals("")){
            JOptionPane.showMessageDialog(this, "Tiền giảm không được để trống", "Invalidation", JOptionPane.ERROR_MESSAGE);
            return;
        }else if(sdt.trim().equals("")){
            JOptionPane.showMessageDialog(this, "Số điện thoại không được để trống", "Invalidation", JOptionPane.ERROR_MESSAGE);
            return;
        }else{
        SimpleDateFormat dateFM = new SimpleDateFormat("YYYY-MM-dd");
        int trangThai = 0;
        if (cboTrangThai.getSelectedItem().toString().equalsIgnoreCase("Đã Thanh Toán")) {
            trangThai = 1;
        }
        JOptionPane.showMessageDialog(this, hdSer.update(tblHoaDon.getValueAt(tblHoaDon.getSelectedRow(), 0).toString(), new HoaDon(txtMaHD.getText(), txtTenXe.getText(), txtTenNV.getText(), txtTenKH.getText(),
                dateFM.format(txtNgayTao.getDate()), dateFM.format(txtNgayThanhToan.getDate()), Long.parseLong(txtKhachTra.getText()), Integer.parseInt(txtTongTien.getText()), Integer.valueOf(txtSoTienGiam.getText()), txtSoDienThoai.getText(),
                rdoYesBH.isSelected() == true ? 1 : 0, rdoYesLB.isSelected() == true ? 1 : 0, trangThai, txtNote.getText())));
        list = hdSer.getAll();
        loadTable(list);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        String ma = txtTim.getText().trim();
        List<HoaDon> lst = hdSer.getOneSP(ma);
        if (ma.trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Nhập sản phẩm cần tìm");
            return;
        }
        if (lst.size() == 0) {
            JOptionPane.showMessageDialog(this, "Không tìm thấy");
            return;
        } else {
            loadTable(lst);
            JOptionPane.showMessageDialog(this, "Đã tìm thấy");
            return;
        }

    }//GEN-LAST:event_jButton7ActionPerformed

    private void tblHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoaDonMouseClicked
        // TODO add your handling code here:

        int row = tblHoaDon.getSelectedRow();
        if (row == -1) {
            return;
        }
        ViewHoaDonCT view = new ViewHoaDonCT(tblHoaDon.getValueAt(row, 0).toString());
        view.setVisible(true);
        String maHD = tblHoaDon.getValueAt(row, 0).toString();
        String tenXe = tblHoaDon.getValueAt(row, 1).toString();
        String tenNV = tblHoaDon.getValueAt(row, 2).toString();
        String tenKH = tblHoaDon.getValueAt(row, 3).toString();
        try {
            tblHoaDon.getSelectedRow();
            Date date = new SimpleDateFormat("yyyy-MM-dd").parse(tblHoaDon.getValueAt(row, 4).toString());
            txtNgayTao.setDate(date);
        } catch (Exception e) {

        }
        try {
            tblHoaDon.getSelectedRow();
            Date date = new SimpleDateFormat("yyyy-MM-dd").parse(tblHoaDon.getValueAt(row, 5).toString());
            txtNgayThanhToan.setDate(date);
        } catch (Exception e) {
        }
        String khachTra = tblHoaDon.getValueAt(row, 6).toString();
        String tongTien = tblHoaDon.getValueAt(row, 7).toString();
        String soTienGiam = tblHoaDon.getValueAt(row, 8).toString();
        String soDienThoai = tblHoaDon.getValueAt(row, 9).toString();
        String trangThai = tblHoaDon.getValueAt(row, 12).toString();

        if (tblHoaDon.getValueAt(row, 10).toString().equalsIgnoreCase("Có")) {
            rdoYesBH.setSelected(true);
        } else {
            rdoNoBH.setSelected(true);
        }
        if (tblHoaDon.getValueAt(row, 11).toString().equalsIgnoreCase("Có")) {
            rdoYesLB.setSelected(true);
        } else {
            rdoNoLB.setSelected(true);
        }

        txtMaHD.setText(maHD);
        txtTenXe.setText(tenXe);
        txtTenNV.setText(tenNV);
        txtTenKH.setText(tenKH);
        txtTongTien.setText(tongTien);
        txtSoTienGiam.setText(soTienGiam);
        txtSoDienThoai.setText(soDienThoai);
        txtKhachTra.setText(khachTra);
        if (trangThai == "Đã Thanh Toán") {
            cboTrangThai.setSelectedIndex(0);
        } else {
            cboTrangThai.setSelectedIndex(1);
        }
        String note = tblHoaDon.getValueAt(row, 13).toString();
        txtNote.setText(note);
    }//GEN-LAST:event_tblHoaDonMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        try {
            XSSFWorkbook wb = new XSSFWorkbook();
            XSSFSheet sheet = wb.createSheet("danhsach");
            XSSFRow row = null;
            Cell cell = null;
            row = sheet.createRow(3);
            cell = row.createCell(0, CellType.STRING);
            cell.setCellValue("STT");
            cell = row.createCell(1, CellType.STRING);
            cell.setCellValue("MÃ HÓA ĐƠN");
            cell = row.createCell(2, CellType.STRING);
            cell.setCellValue("TÊN XE");
            cell = row.createCell(3, CellType.STRING);
            cell.setCellValue("TÊN NHÂN VIÊN");
            cell = row.createCell(4, CellType.STRING);
            cell.setCellValue("TÊN KHÁCH HÀNG");
            cell = row.createCell(5, CellType.STRING);
            cell.setCellValue("NGÀY TẠO");
            cell = row.createCell(6, CellType.STRING);
            cell.setCellValue("NGÀY THANH TOÁN");
            cell = row.createCell(7, CellType.STRING);
            cell.setCellValue("KHÁCH TRẢ");
            cell = row.createCell(8, CellType.STRING);
            cell.setCellValue("TỔNG TIỀN");
            cell = row.createCell(9, CellType.STRING);
            cell.setCellValue("SỐ TIỀN GIẢM");
            cell = row.createCell(10, CellType.STRING);
            cell.setCellValue("SĐT");
            cell = row.createCell(11, CellType.STRING);
            cell.setCellValue("BẢO HIỂM");
            cell = row.createCell(12, CellType.STRING);
            cell.setCellValue("LÀM BIỂN");
            cell = row.createCell(13, CellType.STRING);
            cell.setCellValue("TRẠNG THÁI");
            cell = row.createCell(14, CellType.STRING);
            cell.setCellValue("NOTE");
            System.out.println(list);
            for (int i = 0; i < list.size(); i++) {
                row = sheet.createRow(4 + i);
                cell = row.createCell(0, CellType.NUMERIC);
                cell.setCellValue(i + 1);
                cell = row.createCell(1, CellType.STRING);
                cell.setCellValue(list.get(i).getMaHD());
                cell = row.createCell(2, CellType.STRING);
                cell.setCellValue(list.get(i).getTenXe());
                cell = row.createCell(3, CellType.STRING);
                cell.setCellValue(list.get(i).getTenNV());
                cell = row.createCell(4, CellType.STRING);
                cell.setCellValue(list.get(i).getTenKH());
                cell = row.createCell(5, CellType.STRING);
                cell.setCellValue(list.get(i).getNgayTao());
                cell = row.createCell(6, CellType.STRING);
                cell.setCellValue(list.get(i).getNgayThanhToan());
                cell = row.createCell(7, CellType.STRING);
                cell.setCellValue(list.get(i).getKhachTra());
                cell = row.createCell(8, CellType.STRING);
                cell.setCellValue(list.get(i).getTongTien());
                cell = row.createCell(9, CellType.STRING);
                cell.setCellValue(list.get(i).getSoTienGiam());
                cell = row.createCell(10, CellType.STRING);
                cell.setCellValue(list.get(i).getSdtNguoiNhan());
                cell = row.createCell(11, CellType.STRING);
                cell.setCellValue(list.get(i).getBaoHiem() == 1 ? "Có" : "Không");
                cell = row.createCell(12, CellType.STRING);
                cell.setCellValue(list.get(i).getLamBien() == 1 ? "Có" : "Không");
                cell = row.createCell(13, CellType.STRING);
                cell.setCellValue(list.get(i).getTrangThai() == 1 ? "Đã Thanh Toán" : "Chưa Thanh Toán");

                cell = row.createCell(14, CellType.STRING);
                cell.setCellValue(list.get(i).getNote());
            }
            File file = new File("E:\\Excel\\danhsachhoadon.xlsx");
            try {
                FileOutputStream fos = new FileOutputStream(file);
                wb.write(fos);
                fos.close();
            } catch (FileNotFoundException e) {
                e.printStackTrace();
            } catch (IOException ex) {
                ex.printStackTrace();
            }
            JOptionPane.showMessageDialog(this, "Xuất file excel thành công!!!!");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cboTrangThai;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton rdoNoBH;
    private javax.swing.JRadioButton rdoNoLB;
    private javax.swing.JRadioButton rdoYesBH;
    private javax.swing.JRadioButton rdoYesLB;
    private javax.swing.JTable tblHoaDon;
    private javax.swing.JTextField txtKhachTra;
    private javax.swing.JTextField txtMaHD;
    private com.toedter.calendar.JDateChooser txtNgayTao;
    private com.toedter.calendar.JDateChooser txtNgayThanhToan;
    private javax.swing.JTextArea txtNote;
    private javax.swing.JTextField txtSoDienThoai;
    private javax.swing.JTextField txtSoTienGiam;
    private javax.swing.JTextField txtTenKH;
    private javax.swing.JTextField txtTenNV;
    private javax.swing.JTextField txtTenXe;
    private javax.swing.JTextField txtTim;
    private javax.swing.JTextField txtTongTien;
    // End of variables declaration//GEN-END:variables
}
